name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  pr:
    name: pull_request
    if: "github.event_name == 'pull_request'"
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        toolchain:
          - stable
          - nightly
    runs-on: ${{ matrix.os }}
    needs: lint
    steps:
      - name: checkout the source code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        if: ${{ matrix.toolchain == 'stable' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: '--lib -- --skip medium'
  master:
    name: push
    if: "github.event_name == 'push'"
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        toolchain:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    needs: lint
    steps:
      - name: checkout the source code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        if: ${{ matrix.toolchain == 'stable' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: '--lib -- --skip medium'
  lint:
    name: lint
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        toolchain:
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout the source code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
      - name: fmt
        if: ${{ matrix.toolchain == 'nightly' }}
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: clippy
        if: ${{ matrix.toolchain == 'nightly' }}
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings -A clippy::type_complexity
  cargo-audit:
    name: cargo-audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  code-coverage:
    name: code-coverage
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - uses: actions-rs/grcov@v0.1